### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by bkacjios** [bkacjios/m-overlay#117]
- [x] Add a `CheckPanel` as a complement to `RadioPanel` (Use bitwise flags to make saving values more efficient)
- [x] Remove `Loop mode` radio box.
- [x] Make `Playlist mode` default and use a `CheckPanel` for setting when you would like your music to loop.
- [x] Make `Loop menu` checkbox
- [x] Make `Loop stage (timed)` checkbox
- [x] Make `Loop stage (endless)` checkbox

**Comment by ribbanya** [comment]
>  Add a radio option panel for enabling Beyond Melee & Akaneia features since detecting the mods seems difficult.

Just so you know for sizing purposes, I was planning on adding SD Remix stage support.
